db:
  image: million12/mariadb:latest
  ports:
    - 3306
  environment:
    MARIADB_PASS: rootpw

web:
  image: million12/typo3-neos
  ports:
    - '80:80'
  links:
    - db:db
  environment:
    T3APP_VHOST_NAMES: maltnmore dev.maltnmore behat.dev.maltnmore
    T3APP_BUILD_REPO_URL: "https://github.com/GerDner/mnm_base.git"
    T3APP_BUILD_BRANCH: master 
    T3APP_NEOS_SITE_PACKAGE: Bucher.Maltnmore
    T3APP_ALWAYS_DO_PULL: 'true'

dev:
  image: million12/php-app-ssh
  ports:
    - '1122:22'
  links:
    - db:db
    - web:web
  volumes_from:
    - web
  environment:
    IMPORT_GITHUB_PUB_KEYS: GerDner